services:
  - type: web
    name: viveiro-comurg-backend
    env: node
    plan: free
    buildCommand: "cd backend && npm install"
    startCommand: "cd backend && node server.js"
    envVars:
      - key: SENDGRID_API_KEY
        sync: false
      - key: CONTACT_EMAIL
        sync: false
      - key: VITE_API_URL
        value: "https://viveiro-comurg-backend.onrender.com"

