services:
  - type: web
    name: viveiro-comurg-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "npm start"

  - type: web
    name: viveiro-comurg-frontend
    env: static
    plan: free
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    publishPath: dist
    envVars:
      - key: VITE_API_URL
        value: "https://viveiro-comurg-backend-yjsj.onrender.com"
