services:
  - type: web
    name: viveiro-comurg-backend
    env: node
    plan: free
    buildCommand: "cd backend && npm install"
    startCommand: "cd backend && node server.js"

  - type: static
    name: viveiro-comurg-frontend
    buildCommand: "cd frontend && npm install && npm run build"
    publishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: "https://viveiro-comurg-backend-yjsj.onrender.com"
