services:
  - type: web
    name: viveiro-comurg-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: CONTACT_EMAIL
        sync: false
      - key: SENDGRID_API_KEY
        sync: false

  - type: web
    name: viveiro-comurg-frontend
    env: static
    plan: free
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    publishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: "https://viveiro-comurg-backend-yjsj.onrender.com"
