name: Deploy to Render

on:
  push:
    branches: [ main, master ]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render backend deploy
        run: |
          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID_BACKEND }}/deploys"             -H "Accept: application/json"             -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"             -d ''

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render frontend deploy
        run: |
          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID_FRONTEND }}/deploys"             -H "Accept: application/json"             -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"             -d ''
